'use strict';
const config=window.PATU_CONFIG;
const $=(q)=>document.querySelector(q);
const escapeHTML=(value)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categories=['Todos','Tradicionais','Especiais','Gourmet','Tamanhos','Combos'];
$('.filters').innerHTML=categories.map((c,i)=>`<button type="button" data-filter="${c}" aria-pressed="${i===0}">${c}</button>`).join('');
function renderProducts(category='Todos'){
 $('.products').innerHTML=config.products.filter(p=>category==='Todos'||p.category===category).map(p=>`<article class="product"><div class="product-image"><img src="${escapeHTML(p.image)}" alt="Imagem ilustrativa de pudim; substituir pela foto de ${escapeHTML(p.name)}" loading="lazy"><span>EXEMPLO · ${escapeHTML(p.category.toUpperCase())}</span></div><div class="product-body"><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.description)}</p><small>Imagem ilustrativa · sabor e preço a confirmar</small><div class="product-bottom"><strong>${escapeHTML(p.price)}</strong><button data-order="${escapeHTML(p.name)}" aria-label="Pedir ${escapeHTML(p.name)}">Pedir ↗</button></div></div></article>`).join('');
}
renderProducts();
$('.filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderProducts(b.dataset.filter);});
const values=[['♧','Produção artesanal','Ingredientes e preparo cuidadoso.'],['✧','Qualidade','Cada detalhe pensado para uma ótima experiência.'],['♡','Feito com carinho','Para tornar os momentos ainda mais especiais.'],['◇','Para presentear','Um jeito doce de surpreender alguém.'],['✳','Toda ocasião','Do almoço em família à grande comemoração.']];
$('.values').innerHTML=values.map(v=>`<article class="value"><span aria-hidden="true">${v[0]}</span><h3>${v[1]}</h3><p>${v[2]}</p></article>`).join('');
$('.occasion-grid').innerHTML=[['♧','Aniversários'],['✧','Festas'],['♡','Casamentos'],['▱','Corporativo'],['◇','Presentes'],['✳','Datas especiais']].map(v=>`<a class="occasion" href="#eventos"><span aria-hidden="true">${v[0]}</span><h3>${v[1]}</h3></a>`).join('');
$('.gallery').innerHTML=['A beleza de um clássico','Calda que encanta','De pertinho, ainda melhor','Um convite para compartilhar'].map((t,i)=>`<button type="button" data-gallery aria-label="Ampliar imagem: ${t}"><img src="pudim.jpg" alt="${t} — imagem demonstrativa" loading="lazy" style="object-position:${[45,25,75,50][i]}% ${[50,65,45,70][i]}%"><span>${t} ↗</span></button>`).join('');
$('.feed').innerHTML=[30,60,80].map(p=>`<a href="https://www.instagram.com/patu.pudins/" target="_blank" rel="noopener noreferrer" aria-label="Visitar Instagram da Patu"><img src="pudim.jpg" alt="Composição de feed demonstrativa" style="object-position:${p}%" loading="lazy"></a>`).join('');
$('.reviews').innerHTML=config.reviews.map(r=>`<article class="review"><span class="stars" aria-label="Estrelas ilustrativas, sem nota real">☆☆☆☆☆</span><p>“${escapeHTML(r.text)}”</p><small>${escapeHTML(r.name)}<br>Avaliação a inserir</small></article>`).join('');
const faqs=[['Quais sabores estão disponíveis?','[Insira os sabores reais.] O cardápio deste protótipo é demonstrativo. Consulte a disponibilidade com a empresa.'],['Qual o tamanho dos pudins?','[Insira tamanhos, pesos e porções reais.]'],['Como faço meu pedido?','Escolha um produto e clique em Pedir. Após a configuração do WhatsApp da empresa, você poderá encaminhar sua mensagem e confirmar a disponibilidade.'],['Vocês fazem entregas?','[Insira as regiões atendidas, taxas e condições de entrega.]'],['Posso encomendar para festas?','Utilize o formulário de eventos para preparar sua consulta. [Confirmar opções e disponibilidade com a marca.]'],['Com quanto tempo de antecedência devo encomendar?','[Insira o prazo mínimo de encomenda informado pela empresa.]'],['Quais são as formas de pagamento?','[Insira as formas de pagamento aceitas.]'],['Posso fazer um pedido personalizado?','[Insira as possibilidades de personalização.] Consulte a empresa antes de confirmar seu pedido.']];
$('.faqs').innerHTML=faqs.map(f=>`<details><summary>${f[0]}</summary><p>${f[1]}</p></details>`).join('');
const menu=$('.menu-toggle'); menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fechar menu':'Abrir menu');$('nav').classList.toggle('open',open);});
$('nav').addEventListener('click',e=>{if(e.target.closest('a')){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menu');$('nav').classList.remove('open');}});
const dialog=$('#order-dialog');let lastFocus;
function openOrder(product){lastFocus=document.activeElement;$('#order-form').reset();$('#order-form').hidden=false;$('#message-preview').hidden=true;$('#copy-status').textContent='';$('#order-form [name=produto]').value=product;dialog.showModal();}
function prepareMessage(message){const number=config.WHATSAPP_NUMBER.replace(/\D/g,'');if(number.length>=10&&number.length<=15){window.open(`https://wa.me/${number}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');return;}if(!dialog.open){lastFocus=document.activeElement;dialog.showModal();}$('#order-form').hidden=true;$('#message-preview').hidden=false;$('#message-preview textarea').value=message;$('#message-preview .copy').focus();}
document.addEventListener('click',e=>{const order=e.target.closest('[data-order]');if(order)openOrder(order.dataset.order);if(e.target.closest('[data-gallery]')){lastFocus=document.activeElement;$('#lightbox').showModal();}});
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.addEventListener('close',()=>lastFocus?.focus());});
$('#order-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);prepareMessage(`Olá! Gostaria de fazer um pedido na Patu Pudins.\n\nProduto: ${data.get('produto')}\nQuantidade: ${data.get('quantidade')}\nObservações: ${data.get('observacoes')||'Nenhuma'}\n\nGostaria de saber a disponibilidade e como posso realizar o pagamento.`);});
const dateInput=$('#event-form [name=data]');const today=new Date();dateInput.min=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
$('#event-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);prepareMessage(`Olá! Gostaria de um orçamento para evento na Patu Pudins.\n\nNome: ${data.get('nome')}\nWhatsApp: ${data.get('whatsapp')}\nEvento: ${data.get('evento')}\nData: ${data.get('data').split('-').reverse().join('/')}\nQuantidade aproximada: ${data.get('quantidade')}\nMensagem: ${data.get('mensagem')||'Nenhuma'}\n\nPodemos conversar sobre disponibilidade e valores?`);});
$('.copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#message-preview textarea').value);$('#copy-status').textContent='Mensagem copiada. Nenhum pedido foi enviado.';}catch{$('#message-preview textarea').select();$('#copy-status').textContent='Selecione e copie o texto da mensagem acima.';}});
if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('reveal');observer.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.section-top,.intro,.feature-copy,.value,.steps article').forEach(e=>observer.observe(e));}
if(config.business){const schema=document.createElement('script');schema.type='application/ld+json';schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':'LocalBusiness',...config.business});document.head.append(schema);}
